/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_RESOURCES_FILES           2
#define MMAP_RESOURCES_CHECKSUM        0xAD37

enum MMAP_RESOURCES_LISTS {
    MMAP_RESOURCES_DATA_JSON = 0,        /*!< data.json */
    MMAP_RESOURCES_SETTING_SPNG = 1,        /*!< setting.spng */
};
