/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPIFFS_FILES           1
#define MMAP_SPIFFS_CHECKSUM        0xBF49

enum MMAP_SPIFFS_LISTS {
    MMAP_SPIFFS_SETTING_SPNG = 0,        /*!< setting.spng */
};
