#ifndef USE_STYLE
#define USE_STYLE

#define SCREEN_H_RES 368
#define SCREEN_V_RES 448

#define LAYOUT_CTL_PANEL_HEIGHT 42
#define LAYOUT_HEADER_BAR_PAD_TOP 6
#define LAYOUT_HEADER_BAR_PAD_LEFT 24
#define LAYOUT_HEADER_BAR_PAD_RIGHT 24

#define LAYOUT_LOTTIE_AREA_H 160
#define LAYOUT_LOTTIE_AREA_W 240

#define LAYOUT_TEXT_AREA_W 320
#define LAYOUT_TEXT_AREA_H 180

#define LAYOUT_STATUS_HEIGHT 66
#define LAYOUT_STATUS_PAD_BOTTOM 6
#define LAYOUT_STATUS_PAD_LEFT 12
#define LAYOUT_STATUS_PAD_RIGHT 12

#define ICON_INACTIVE_H 32
#define ICON_INACTIVE_W 32

#define BTN_MAIN_SIZE 48
#define BTN_TOP_PADDING 24

#define BAT_COLOR_FG_NORMAL (0x000000)
#define BAT_COLOR_FG_CHARGING (0x000000)
#define BAT_COLOR_BG_NORMAL (0xffffff)
#define BAT_COLOR_BG_CHARGING (0x38ff77)

#define BAT_WIDTH 48
#define BAT_HEIGHT 24
#define BAT_PADDING 24
#define BAT_RADIUS 10

#define WIN_WIFI_LIST_HEADER_HEIGHT (BTN_MAIN_SIZE + 12)
#define WIN_WIFI_LIST_TITLE_FG (0xffffff)

#endif