#ifndef USE_STYLE
#define USE_STYLE

#define SCREEN_H_RES 368
#define SCREEN_V_RES 448

#define BTN_MAIN_SIZE 36
#define BTN_TOP_PADDING 24

#define LAYOUT_CTL_PANEL_HEIGHT 44

#define ICON_WIFI_SIZE 32

#define LOTTIE_SIZE 160

#define BAT_COLOR_FG_NORMAL (0x000000)
#define BAT_COLOR_FG_CHARGING (0x000000)
#define BAT_COLOR_BG_NORMAL (0xffffff)
#define BAT_COLOR_BG_CHARGING (0x2ced9d)

#define BAT_WIDTH 48
#define BAT_HEIGHT 24
#define BAT_PADDING 24
#define BAT_RADIUS 12

#endif